version: '3.8'
services:
    nginx:
        image: nginx:1.19.1-alpine
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - .:/app
            - ./docker/nginx/conf/local.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php7
        networks:
            - api

    php7:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                DOCKER_UID: ${DOCKER_UID:-0}
                DOCKER_GID: ${DOCKER_GID:-0}
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        command: sh /docker-entrypoint.sh
        depends_on:
            - database
        networks:
            - api

    node:
        image: node:15.12.0-alpine
        working_dir: /app
        volumes:
            - .:/app
        env_file:
            - .env
        networks:
            - api

    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - ${MYSQL_HOST_PORT}:${DB_PORT}
        volumes:
            - data:/var/lib/mysql
        networks:
            - api

volumes:
    data:
        driver: local

networks:
    api:
        driver: bridge
